# Generated by Django 5.2.6 on 2025-10-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='course_subject',
            field=models.TextField(blank=True),
        ),
    ]
