# Generated by Django 5.2.6 on 2025-10-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_alter_tutor_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='course_subject',
            field=models.CharField(default=None),
        ),
    ]
