# Generated by Django 5.2.6 on 2025-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutor_photo_1_tutor_photo_2_tutor_photo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.CharField(default=1, help_text='Years of experience', max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from 0.0 to 5.0', max_digits=2),
        ),
        migrations.AddField(
            model_name='tutor',
            name='taught_students',
            field=models.PositiveIntegerField(default=100, help_text='Number of students taught'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='course_subject',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Math', 'Math'), ('liberal Studies', 'Liberal Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Chinese', help_text='Subject taught by the tutor', max_length=50),
        ),
    ]
