# Generated by Django 5.2.6 on 2025-10-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0004_alter_tutor_course_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_enrolled', models.PositiveIntegerField(default=0, help_text='Number of students enrolled')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from 0.0 to 5.0', max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, help_text='Course price (e.g., 130.00)', max_digits=8)),
                ('duration', models.DurationField(help_text='Total length of the course (HH:MM:SS)')),
                ('class_type', models.CharField(choices=[('live', 'Live'), ('video', 'Video')], default='live', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutors.tutor')),
            ],
        ),
    ]
