# Generated by Django 5.2.6 on 2025-10-21 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tutors', '0004_alter_tutor_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=0, help_text='Name of the course', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_type',
            field=models.CharField(choices=[('live', 'Live'), ('video', 'Video')], default='live', help_text='Delivery format of the course', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Course price in USD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(help_text='Tutor teaching this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutors.tutor'),
        ),
    ]
