# Generated by Django 5.2.6 on 2025-10-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_title_alter_course_class_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.CharField(default='Wed 4 p.m.', help_text='Scheduled time for the class (e.g., Wed 4 p.m.)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=1, help_text='Course duration in weeks'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_classes',
            field=models.PositiveIntegerField(default=1, help_text='Total number of classes in the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Course price in HKD', max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Name of the course', max_length=200),
        ),
    ]
