# Generated by Django 5.2.6 on 2025-10-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_duration_course_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of students allowed'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.CharField(help_text='Scheduled time for the class (e.g., Wed 4 p.m.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.PositiveIntegerField(default=0, help_text='Current number of students enrolled'),
        ),
    ]
