# Generated by Django 5.2.6 on 2025-10-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_max_students_alter_course_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo_main',
            field=models.ImageField(default=0, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
