# Generated by Django 5.2.6 on 2025-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_photo_1_course_photo_2_course_photo_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='course',
            name='district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Kowloon City', 'Kowloon City'), ('Kwun Tong', 'Kwun Tong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Central & Western', 'Central & Western'), ('Eastern', 'Eastern'), ('Southern', 'Southern'), ('Wan Chai', 'Wan Chai')], default='Sha Tin', help_text='District where the course is offered', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=1.5, help_text='Course duration in hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Math', 'Math'), ('liberal Studies', 'Liberal Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Chinese', help_text='Subject matter of the course', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.CharField(default='Wed 4 p.m.', help_text='Scheduled time for the class (e.g., Wed 4 p.m.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_classes',
            field=models.PositiveIntegerField(default=4, help_text='Total number of classes in the course'),
        ),
    ]
