# Generated by Django 5.2.6 on 2025-10-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_duration_weeks_course_district_and_more'),
        ('schools', '0002_delete_subject'),
        ('tutors', '0004_alter_tutor_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School offering the course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(help_text='Tutor teaching this course', on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='tutors.tutor'),
        ),
    ]
