# Generated by Django 5.2.6 on 2025-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_school_alter_course_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the course', null=True),
        ),
    ]
