# Generated by Django 5.2.6 on 2025-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Chinese', 'Chinese'), ('English', 'English'), ('Math', 'Math'), ('liberal Studies', 'Liberal Studies'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default='Chinese', help_text='Subject matter of the curriculum', max_length=50)),
                ('text', models.TextField(blank=True, help_text='Detailed syllabus of the curriculum', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.ManyToManyField(blank=True, to='courses.curriculum'),
        ),
    ]
