# Generated by Django 5.2.6 on 2025-11-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_curriculum_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=2, help_text='Course duration in hours', max_digits=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=500, help_text='Course price in HKD', null=True),
        ),
    ]
